apiVersion: v1
kind: Pod
metadata:
  name: lr-pod
  namespace: do15-lr
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 300m
  terminationGracePeriodSeconds: 0
