apiVersion: v1
kind: Pod
metadata:
  name: qos-limit-only
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
  terminationGracePeriodSeconds: 0
