apiVersion: v1
kind: Pod
metadata:
  name: notbesteffort-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: 8Mi
  terminationGracePeriodSeconds: 0
