apiVersion: v1
kind: Pod
metadata:
  name: nginx-name1
spec:
  containers:
  - name: nginx-ctnr
    image: nginx:alpine
    imagePullPolicy: Always
    command: []
    args: ["nginx", "-g", "daemon off;"]
    env:
    - name: NEKO
      value: nyan
    ports:
    - containerPort: 80
      protocol: TCP
    workingDir: /tmp
