apiVersion: v1
kind: Pod
metadata:
  name: usepod
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["tail", "-f", "/dev/null"]
    env:
    - name: conf-v
      valueFrom:
        configMapKeyRef:
          name: conf
          key: sakura
    - name: sec-v1
      valueFrom:
        secretKeyRef:
          name: sec
          key: password
          optional: true
    envFrom:
    - configMapRef:
        name: cm-data
    - prefix: SEC_
      secretRef:
        name: secret-data
  terminationGracePeriodSeconds: 0
