apiVersion: v1
kind: Pod
metadata:
  name: usepod2
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: cm-volume
      mountPath: /config
    - name: secret-volume
      mountPath: /etc/secrets
    - name: secret-volume2
      mountPath: /secrets
  volumes:
  - name: cm-volume
    configMap:
      name: cm-data
  - name: secret-volume
    secret:
      secretName: sec
      defaultMode: 0600
      items:
      - key: cred.txt
        path: creds/sec.txt
        mode: 0400
  - name: secret-volume2
    secret:
      secretName: sec
  terminationGracePeriodSeconds: 0
