apiVersion: v1
kind: Pod
metadata:
  name: usepod
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: conf-v
      mountPath: /configh
    - name: sec-v1
      mountPath: /etc/secretsh
    - name: sec-v2
      mountPath: /secretsh
  volumes:
  - name: conf-v
    configMap:
      name: conf
      optional: True
  - name: sec-v1
    secret:
      secretName: sec
      defaultMode: 0600
      items:
      - key: cred.txt
        path: creds/sec.txt
        mode: 0400
  - name: sec-v2
    secret:
      secretName: sec
  terminationGracePeriodSeconds: 0
