apiVersion: v1
kind: Pod
metadata:
  name: check
spec:
  containers:
  - image: nginx
    name: container
    livenessProbe:
      httpGet:
        port: 80
        path: /
      failureThreshold: 5
      periodSeconds: 5
  - image: nginx
    name: container
    livenessProbe:
      httpGet:
        port: 80
        path: /
      failureThreshold: 10
      periodSeconds: 5
