apiVersion: v1
kind: Pod
metadata:
  name: readiness
  labels:
    app: lbl
spec:
  containers:
  - image: nginx
    name: ctnr
    readinessProbe:
      httpGet:
        port: 80
        path: /
      failureThreshold: 1
      periodSeconds: 1
