apiVersion: v1
kind: Namespace
metadata:
  name: do17
---
apiVersion: v1
kind: Pod
metadata:
  name: do17-label
  labels:
    name: nginx
    environment: dev
  namespace: do17
spec:
  containers:
  - name: nginx
    image: nginx:alpine
  terminationGracePeriodSeconds: 0
