apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demon
spec:
  selector:
    matchLabels:
      app: apple
  template:
    metadata:
      labels:
        app: apple
    spec:
      containers:
        - image: fluent/fluentd
          name: fluentd
