apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-m
spec:
  replicas: 10
  selector:
    matchLabels:
      app: podinfo-lbl
  template:
    metadata:
      labels:
        app: podinfo-lbl
    spec:
      containers:
      - image: stefanprodan/podinfo
        name: podinfo-cnt
        ports:
        - containerPort: 9898
          protocol: TCP
