apiVersion: v1
kind: Pod
metadata:
  name: dojo5
spec:
  containers:
  - name: dojo5-1
    image: alpine
    command: ["sh", "-c"]
    args:
    - |
      exec >> /var/log/date-tail/output.log
      echo -n 'Start at: '
      while true; do
        date
        sleep 1
      done
    volumeMounts:
    - name: vol-mnt
      mountPath: /var/log/date-tail
  - name: dojo5-2
    image: alpine
    command: ["sh", "-c"]
    args:
    - |
      tail -f /var/log/date-tail/output.log
    volumeMounts:
    - name: vol-mnt
      mountPath: /var/log/date-tail
  volumes:
  - name: vol-mnt
    emptyDir:
  terminationGracePeriodSeconds: 0
