apiVersion: v1
kind: Pod
metadata:
  name: res
spec:
  containers:
  - image: nginx
    name: ng1
    resources:
      requests:
        cpu: 25m
        memory: 4Mi
      limits:
        cpu: 400m
        memory: 128Mi
