apiVersion: v1
kind: Pod
metadata:
  name: fsgr
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: vol
      mountPath: /dat
  volumes:
  - name: vol
    emptyDir:
  terminationGracePeriodSeconds: 0
