apiVersion: v1
kind: Namespace
metadata:
  name: d18
---
apiVersion: v1
kind: Pod
metadata:
  name: host-t8m9
  namespace: d18
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - gke-cluster-1-default-pool-d3132b3b-c5wj
  containers:
  - name: nginx
    image: nginx:alpine
