apiVersion: v1
kind: Pod
metadata:
  name: host-not-c5wj
  namespace: d18
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - gke-cluster-1-default-pool-d3132b3b-c5wj
  containers:
  - name: nginx
    image: nginx:alpine
