apiVersion: v1
kind: Pod
metadata:
  name: host-xxxx
  namespace: d18
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - gke-cluster-1-default-pool-d3132b3b-xxxx
  containers:
  - name: nginx
    image: nginx:alpine
